Add like button and save conversation
bioimage-io/bioimageio-chatbot pull request #21
Opened 2023-11-06 05:39 UTC by alalulu8668

add like button to collect feedback, store each session (with user feedback) as json file.

2023-11-06 06:31 UTC, oeway requested changes

2023-11-06 06:31 UTC, oeway commented on bioimageio_chatbot/chatbot.py
> +    with open(chat_log_path, 'w', encoding='utf-8') as file:
Would be better if we use aiofiles to write it: https://github.com/Tinche/aiofiles

2023-11-06 06:31 UTC, oeway commented on bioimageio_chatbot/chatbot.py
> +        print(f"UserFeedback: {user_report}")
We need to call the save chat history here too. The difference is that it should contain additional key "comment" and "like", and save in a different folder.

2023-11-11 22:56 UTC, oeway commented on bioimageio_chatbot/static/index.html
> +            Send Feedback
Change to `Submit`

2023-11-11 22:57 UTC, oeway commented on bioimageio_chatbot/static/index.html
> +        type: 'general feedback', // Set the type to 'general feedback'
Maybe change to `type: 'general'`

2023-11-11 22:58 UTC, oeway commented on bioimageio_chatbot/chatbot.py
> +    server_url = "https://chat.bioimage.io"
Change back to `https://ai.imjoy.io`

2023-11-11 23:00 UTC, oeway commented on requirements.txt
> +aiofiles
Add a new line

2023-11-11 23:02 UTC, alalulu8668 commented
All updates according to Wei's comments.

2023-11-11 23:10 UTC, oeway approved these changes
Thanks! Looks good to me now!

2023-11-11 23:10 UTC, merged